version: "3.9"

services:
  app:
    build: ./api
    container_name: chronicle_store_api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: nestdb
    command: npm run start:dev

  db:
    image: postgres:17.9
    container_name: nest-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: